languageCode = "pt-pt"
languageName = "Português (Portugal)"
weight = 5
title = "Caoeuu"

[params]
  displayName = "Português (Portugal)"
  isoCode = "pt-pt"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = "img/logo.png"
  description = "Me and My Jumpjump Team"

[params.author]
  name = "Xiaocao"
  image = "images/avatar.jpg"
  headline = "Me and My Jumpjump Team"
  bio = "Me and My Jumpjump Team"
  links = []
