languageCode = "de"
languageName = "Deutsch"
weight = 3
title = "Caoeuu"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "2. January 2006"
  logo = "img/logo.png"
  description = "Me and My Jumpjump Team"

[params.author]
  name = "Xiaocao"
  image = "images/avatar.jpg"
  headline = "Me and My Jumpjump Team"
  bio = "Me and My Jumpjump Team"
  links = []
