languageCode = "fr"
languageName = "Français"
weight = 2
title = "Caoeuu"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 janvier 2006"
  logo = "img/logo.png"
  description = "Me and My Jumpjump Team"

[params.author]
  name = "Xiaocao"
  image = "images/avatar.jpg"
  headline = "Me and My Jumpjump Team"
  bio = "Me and My Jumpjump Team"
  links = []
