languageCode = "en"
languageName = "English"
weight = 1
title = "Caoeuu"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "Me and My Jumpjump Team"

[params.author]
  name = "Xiaocao"
  email = "nuno@n9o.xyz"
  image = "images/avatar.jpg"
  headline = "Me and My Jumpjump Team"
  bio = "Me and My Jumpjump Team"
  links = []
